name: Markdown Prose Lint

on: [push, pull_request]

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run custom proselint action
        uses: ./.github/actions/proselint
